/*lint:disable:standard:filename*/
package eu.kanade.tachiyomi.animeextension.all.hentaimama

/**
 * Genre and studio taxonomy for HentaiMama's browse URLs:
 * /genre/SLUG/page/N/ and /studio/SLUG/page/N/.
 *
 * Harvested from the site's own navigation and series pages, then validated one
 * by one against the live site: a term only ships when its archive actually
 * renders cards, so a ticked box can never land on an empty list.
 */
internal val GENRES: List<Pair<String, String>> = listOf(
    "3d" to "3D",
    "adventure" to "Adventure",
    "ahegao" to "Ahegao",
    "anal" to "Anal",
    "animal-ears" to "Animal Girls",
    "armpit-fetish" to "Armpit fetish",
    "bdsm" to "BDSM",
    "blackmail" to "Blackmail",
    "blonde" to "Blonde",
    "blowjob" to "Blowjob",
    "bondage" to "Bondage",
    "brainwashed" to "Brainwashed",
    "comedy" to "Comedy",
    "condom" to "Condom",
    "cosplay" to "Cosplay",
    "creampie" to "Creampie",
    "cutefunny" to "Cute &amp; Funny",
    "dark-skin" to "Dark Skin",
    "deepthroat" to "DeepThroat",
    "domination" to "Domination",
    "double-penatration" to "Double Penetration",
    "drama" to "Drama",
    "ecchi" to "Ecchi",
    "elf" to "Elf",
    "facesitting" to "Facesitting",
    "facial" to "Facial",
    "family" to "Family",
    "fantasy" to "Fantasy",
    "female-doctor" to "Female Doctor",
    "female-teacher" to "Female Teacher",
    "femdom" to "Femdom",
    "filmed" to "Filmed",
    "footjob" to "Footjob",
    "futanari" to "Futanari",
    "gangbang" to "Gangbang",
    "gyaru" to "Gyaru",
    "hand-job" to "Hand Job",
    "harem" to "Harem",
    "horny-slut" to "Horny Slut",
    "housewife" to "Housewife",
    "humiliation" to "Humiliation",
    "incest" to "Incest",
    "internal-cumshot" to "Internal Cumshot",
    "lactation" to "Lactation",
    "large-breasts" to "Large Breasts",
    "maid" to "Maid",
    "masturbation" to "Masturbation",
    "megane" to "Megane",
    "milf" to "MILF",
    "mind-break" to "Mind Break",
    "molestation" to "Molestation",
    "ntr" to "NTR",
    "nuns" to "Nuns",
    "nurses" to "Nurses",
    "office-ladies" to "Office Ladies",
    "orgy" to "Orgy",
    "pov" to "POV",
    "pregnant" to "Pregnant",
    "princess" to "Princess",
    "public-sex" to "Public Sex",
    "rape" to "Rape",
    "rim-job" to "Rim job",
    "romance" to "Romance",
    "scat" to "Scat",
    "school-girls" to "School Girls",
    "shimapan" to "Shimapan",
    "short" to "Short",
    "shoutacon" to "Shoutacon",
    "small-breasts" to "Small Breasts",
    "sports" to "Sports",
    "squirting" to "Squirting",
    "step-daughter" to "Step Daughter",
    "step-mother" to "Step Mother",
    "step-sister" to "Step Sister",
    "stocking" to "Stocking",
    "strap-on" to "Strap-on",
    "super-power" to "Super Power",
    "supernatural" to "Supernatural",
    "swimsuit" to "Swimsuit",
    "three-some" to "Three some",
    "tits-fuck" to "Tits Fuck",
    "toys" to "Toys",
    "train-molestation" to "Train Molestation",
    "tsundere" to "Tsundere",
    "ugly-bastard" to "Ugly Bastard",
    "uncensored" to "Uncensored",
    "urination" to "Urination",
    "vanilla" to "Vanilla",
    "virgins" to "Virgins",
    "widow" to "Widow",
    "womb-tattoo" to "Womb Tattoo",
    "x-ray" to "X-Ray",
    "yuri" to "Yuri",
)

internal val STUDIOS: List<Pair<String, String>> = listOf(
    "antechinus" to "Antechinus",
    "bunnywalker" to "Bunnywalker",
    "chippai" to "Chippai",
    "clockup" to "CLOCKUP",
    "collaboration-works" to "Collaboration Works",
    "cotton-doll" to "Cotton Doll",
    "majin" to "Majin",
    "mary-jane" to "Mary Jane",
    "ms-pictures" to "MS Pictures",
    "nag" to "Nag",
    "nur" to "Nur",
    "pink-pineapple" to "Pink Pineapple",
    "queen-bee" to "Queen Bee",
    "selfish" to "Selfish",
    "shouten" to "Shouten",
    "suzuki-mirano" to "Suzuki Mirano",
    "t-rex" to "T-Rex",
    "torudaya" to "Torudaya",
    "umemaro3d" to "Umemaro3D",
    "white-bear" to "White Bear",
)
