/*lint:disable:standard:filename*/
package eu.kanade.tachiyomi.animeextension.all.onlyhentaistuff

/**
 * Category / tag / model vocabulary for the browse URLs
 * (/categories/{slug}/, /tags/{slug}/, /models/{slug}/).
 *
 * Harvested from the site's own taxonomy indexes, then validated term by term:
 * each entry's listing was fetched and only the ones that actually render videos
 * ship, so a ticked box can never land on an empty page.
 */
internal val CATEGORY_TERMS: List<Pair<String, String>> = listOf(
    "anal-sex" to "Anal Sex",
    "animal-girls" to "Animal-girls",
    "bdsm" to "Bdsm",
    "big-tits" to "Big Tits",
    "blowjob" to "Blowjob",
    "cassic-sex" to "Cassic Sex",
    "erotic" to "Erotic",
    "fantasy" to "Fantasy",
    "futanari" to "Futanari",
    "group-sex" to "Group Sex",
    "hardcore" to "Hardcore",
    "incest" to "Incest",
    "kimono" to "Kimono",
    "licking" to "Licking",
    "lolicon" to "Lolicon",
    "magical-girl" to "Magical girl",
    "maids" to "Maids",
    "masturbation" to "Masturbation",
    "no-censor" to "No Censor",
    "nurse" to "Nurse",
    "oral-sex" to "Oral Sex",
    "public-outdoor" to "Public Outdoor",
    "rape" to "Rape",
    "school" to "School",
    "sci-fi" to "Sci Fi",
    "shotacon" to "Shotacon",
    "shounen-ai" to "Shounen Ai",
    "small-tits" to "Small Tits",
    "students" to "Students",
    "stuff-sex" to "Stuff Sex",
    "swimsuit" to "Swimsuit",
    "tentacles" to "Tentacles",
    "twins" to "Twins",
    "virgin" to "Virgin",
    "yaoi" to "Yaoi",
    "yuri" to "Yuri",
)

internal val TAG_TERMS: List<Pair<String, String>> = listOf(
    "2017" to "2017",
    "2018" to "2018",
    "2019" to "2019",
    "2020" to "2020",
    "2021" to "2021",
    "2022" to "2022",
    "2023" to "2023",
    "2024" to "2024",
    "2025" to "2025",
    "2026" to "2026",
    "20thanime" to "20thAnime",
    "3d" to "3D",
    "a-p-p-p" to "A.P.P.P.",
    "a1c-studio" to "A1C_Studio",
    "action" to "Action",
    "adult-source-media" to "Adult Source Media",
    "adventure" to "Adventure",
    "ahegao" to "Ahegao",
    "ahiru-koike" to "Ahiru Koike",
    "aic" to "AIC",
    "aic-plus-studio" to "AIC Plus+ Studio",
    "akatsuki-myuuto" to "Akatsuki Myuuto",
    "akazawa-red" to "Akazawa RED",
    "akemi-kobayashi" to "Akemi Kobayashi",
    "aki-akane" to "Aki Akane",
    "akimi-kawashima" to "Akimi Kawashima",
    "alice-production-studio" to "Alice Production Studio",
    "alice-soft" to "Alice Soft",
    "alien" to "Alien",
    "amana-kouta" to "Amana Kouta",
    "amateur" to "Amateur",
    "amino-tetsurou" to "Amino Tetsurou",
    "amodume-ryuuta" to "Amodume Ryuuta",
    "an-dercen-studio" to "An_DerCen_Studio",
    "anal-sex" to "Anal sex",
    "angels" to "Angels",
    "ani-live-l-studio" to "Ani Live L Studio",
    "anik" to "ANIK",
    "animac" to "Animac",
    "animal" to "Animal",
    "neko" to "Animal-girls",
    "animan" to "AniMan",
    "animate-film-studio" to "Animate Film Studio",
    "animation-21" to "Animation 21",
    "anime-antenna-iinkai" to "Anime Antenna Iinkai",
    "anime-virtual" to "Anime-Virtual",
    "aniplex" to "Aniplex",
    "anpro-studio" to "Anpro Studio",
    "aohashi-yutaka" to "Aohashi Yutaka",
    "aoi-yuuno" to "Aoi Yuuno",
    "apataito-studio" to "Apataito Studio",
    "ara" to "Ara",
    "araki-hideki" to "Araki Hideki",
    "arms" to "ARMS",
    "army" to "Army",
    "art-gallery" to "Art Gallery",
    "asahiro-kakashi" to "Asahiro Kakashi",
    "asami-takashi" to "Asami Takashi",
    "asano-hiro" to "Asano Hiro",
    "asari-yoshitoo" to "Asari Yoshitoo",
    "ascendent-animation" to "Ascendent Animation",
    "ashika-sakura" to "Ashika Sakura",
    "ass-fingering" to "Ass fingering",
    "ass-licking" to "Ass licking",
    "atelier-kaguya" to "Atelier Kaguya",
    "athletic" to "Athletic",
    "atsuko-takahashi" to "Atsuko Takahashi",
    "awai-shigeki" to "Awai Shigeki",
    "ayano-kunio" to "Ayano Kunio",
    "ayuma-sayu" to "Ayuma Sayu",
    "baba-ryuuichi" to "Baba Ryuuichi",
    "banzou-tokita" to "Banzou Tokita",
    "bdsm" to "BDSM",
    "beam-entertainment" to "BEAM Entertainment",
    "big-ass" to "Big ass",
    "big-dick" to "Big Dick",
    "big-tits" to "Big tits",
    "black-train" to "Black Train",
    "blackmail" to "Blackmail",
    "blondes" to "Blondes",
    "blowjob" to "Blowjob",
    "blue-bread-studio" to "Blue bread Studio",
    "blue-cat" to "Blue Cat",
    "blue-eyes-studio" to "Blue Eyes Studio",
    "blue-gale-studio" to "Blue Gale Studio",
    "bomb-cute-bomb-studio" to "BOMB! CUTE! BOMB! Studio",
    "bonus" to "Bonus/Special",
    "boom-boom-douga" to "Boom! Boom! Douga",
    "bootleg" to "BOOTLEG",
    "breakbottle-studio" to "Breakbottle Studio",
    "bride" to "Bride",
    "brunette" to "Brunette",
    "bunnywalker-studio" to "Bunnywalker Studio",
    "butler" to "Butler",
    "caress-communications-studio" to "Caress Communications Studio",
    "caryo-studio" to "CARYO_Studio",
    "celeb" to "Celeb",
    "central-park-media" to "Central Park Media",
    "chaos-project" to "Chaos Project",
    "chi" to "Chi",
    "chichi-no-ya" to "ChiChi No Ya",
    "chikae-kuwabara" to "Chikae Kuwabara",
    "chikan" to "Chikan",
    "chinjao-girl-studo" to "Chinjao Girl Studo",
    "chippai" to "Chippai",
    "ciel" to "Ciel",
    "clamp" to "CLAMP",
    "coach" to "Coach",
    "collaboration-works" to "Collaboration Works",
    "comedy" to "Comedy",
    "comix-wave-films" to "CoMix Wave Films",
    "compilation" to "Compilation",
    "condom" to "Condom",
    "crimson" to "Crimson",
    "critical-mass-video" to "Critical Mass Video",
    "crossdressing" to "Crossdressing/Cosplay",
    "curvy" to "Curvy",
    "cyberframe-studios" to "Cyberframe Studio",
    "d-l-studio" to "D/L Studio",
    "daifuku-suginami" to "Daifuku Suginami",
    "dark" to "Dark",
    "de" to "DE",
    "decensored" to "DECENSORED",
    "demons" to "Demons",
    "denbu-momo" to "Denbu Momo",
    "detective" to "Detective",
    "dezaki-satoshi" to "Dezaki Satoshi",
    "dick-toriishi" to "Dick Toriishi",
    "digital-gear" to "Digital Gear",
    "digital-works" to "Digital Works",
    "doctor" to "Doctor",
    "double-penetration" to "Double Penetration",
    "drama" to "Drama",
    "dream-entertainment" to "Dream Entertainment",
    "drugs" to "Drugs",
    "eastern-star-studio" to "Eastern Star Studio",
    "ebony" to "Ebony",
    "edge" to "EDGE",
    "eguchi-hisashi" to "Eguchi Hisashi",
    "elf" to "Elf",
    "eng-sub" to "Eng",
    "erotic" to "Erotic",
    "ether-kitten" to "Ether Kitten",
    "executive-decision-studio" to "Executive Decision Studio",
    "fairy-dust-studio" to "Fairy Dust Studio",
    "fan-fiction" to "Fan fiction",
    "fanart" to "Fanart",
    "fantasy" to "Fantasy",
    "fap-hero" to "Fap Hero",
    "femdom" to "Femdom",
    "stuff-sex" to "Fetishism / Toys",
    "fingering" to "Fingering",
    "fisting" to "Fisting",
    "five-ways-studio" to "Five Ways Studio",
    "flavors-soft" to "Flavors Soft",
    "foodporn" to "Foodporn",
    "footfetish" to "Footfetish",
    "footjob" to "Footjob",
    "fr" to "FR",
    "frontier-works" to "Frontier Works",
    "fujii-wataru" to "Fujii Wataru",
    "fujimoto-yoshitaka" to "Fujimoto Yoshitaka",
    "fukumoto-kan" to "Fukumoto Kan",
    "fukuta-jun" to "Fukuta Jun",
    "fukutomi-hiroshi" to "Fukutomi Hiroshi",
    "fumihiko" to "Fumihiko",
    "furukawa-hiroyuki" to "Furukawa Hiroyuki",
    "futanari" to "Futanari",
    "fuyumi-shirakawa" to "Fuyumi Shirakawa",
    "game-based" to "Game cut / MCV",
    "gangbang" to "Gangbang",
    "garyuu" to "Garyuu",
    "gay" to "Gay",
    "genki-yuuki" to "Genki Yuuki",
    "ghost" to "Ghost",
    "glasses" to "Glasses",
    "godoy" to "Godoy",
    "gold-bear" to "GOLD BEAR",
    "grand-cru-bourgeois" to "Grand Cru Bourgeois",
    "green-bunny" to "Green Bunny",
    "grizzly-studio" to "GRIZZLY Studio",
    "group-sex" to "Group Sex",
    "habara-tetsu" to "Habara Tetsu",
    "hairy" to "Hairy",
    "half-h-p-studio" to "Half H.P Studio",
    "hamuo" to "Hamuo",
    "handjob" to "Handjob",
    "happinet-pictures" to "Happinet Pictures",
    "hardcore" to "Hardcore",
    "harem" to "Harem",
    "hayakawa-naomi" to "Hayakawa Naomi",
    "heavenly-heaven-studio" to "Heavenly Heaven Studio",
    "hideki-oota" to "Hideki Oota",
    "hideo-ura" to "Hideo Ura",
    "higuchi-yoshitaka" to "Higuchi Yoshitaka",
    "hills" to "HiLLS",
    "himajin" to "Himajin",
    "hiromi-yokoyama" to "Hiromi Yokoyama",
    "hiromichi-matano" to "Hiromichi Matano",
    "hiroshi-matsuda" to "Hiroshi Matsuda",
    "hiroyuki-okuno" to "Hiroyuki Okuno",
    "hisashi-tomii" to "Hisashi Tomii",
    "historic" to "Historic",
    "hokiboshi-studio" to "Hokiboshi Studio",
    "honda-kazuyuki" to "Honda Kazuyuki",
    "honda-pisan" to "Honda Pisan",
    "hoods-entertainment" to "Hoods Entertainment",
    "horie" to "Horie",
    "horror" to "Horror",
    "hosoda-naoto" to "Hosoda Naoto",
    "hot-bear" to "Hot Bear",
    "hypnosis" to "Hypnosis",
    "ichiro-watari" to "Ichiro Watari",
    "idol" to "Idol",
    "ikari-masatou" to "Ikari Masatou",
    "incest" to "Incest",
    "iroha" to "Iroha",
    "ironbell-studio" to "IRONBELL Studio",
    "ishige-rui" to "Ishige Rui",
    "ishigura-rei" to "Ishigura Rei",
    "ishihara-ayumi" to "Ishihara Ayumi",
    "ishihara-megumi" to "Ishihara Megumi",
    "ishii-ao" to "Ishii Ao",
    "ishiodori-hiroshi" to "Ishiodori Hiroshi",
    "it" to "ITA",
    "itaba-hiroshi" to "Itaba Hiroshi",
    "itou-fumio" to "Itou Fumio",
    "itoyoko" to "Itoyoko",
    "j-c-staff" to "J.C.Staff",
    "j-t-p-p" to "J.T.P.P.",
    "jap" to "JAP",
    "japananime" to "JapanAnime",
    "japanhomeanimation" to "JapanHomeAnimation",
    "jinbou-masato" to "Jinbou Masato",
    "jinki-tomoshiyo" to "Jinki Tomoshiyo",
    "jiro-nakano" to "Jiro Nakano",
    "jiro-oiwa" to "Jiro Oiwa",
    "jirou-gyuu" to "Jirou Gyuu",
    "jitaku-studio" to "Jitaku Studio",
    "jof" to "JOF",
    "jsdss-studio" to "JSDSS Studio",
    "jumondo" to "Jumondo",
    "jumondou-studio" to "Jumondou Studio",
    "jun-mitsuoka" to "Jun Mitsuoka",
    "kadokawa-shoten" to "Kadokawa Shoten",
    "kaidou-tsukasa" to "Kaidou Tsukasa",
    "kajikazawa-chie" to "Kajikazawa Chie",
    "kajishima-masaki" to "Kajishima Masaki",
    "kamihara-toshiaki" to "Kamihara Toshiaki",
    "kamitsubo-ryouki" to "Kamitsubo Ryouki",
    "kanade-creative" to "Kanade Creative",
    "kanazawa-katsuma" to "Kanazawa Katsuma",
    "kanbara-toshiaki" to "Kanbara Toshiaki",
    "kaneko-hiraku" to "Kaneko Hiraku",
    "kanenari-tokiwa" to "Kanenari Tokiwa",
    "kasahara-shinpei" to "Kasahara Shinpei",
    "kate-sai-studio" to "Kate_sai_studio",
    "kateisaien-studio" to "Kateisaien Studio",
    "katou-seishirou" to "Katou Seishirou",
    "katsuhisa-yamada" to "Katsuhisa Yamada",
    "katsuma-kanazawa" to "Katsuma Kanazawa",
    "katsupiko-fuji" to "Katsupiko Fuji",
    "katsura-yoshihiro" to "Katsura Yoshihiro",
    "katsuyoshi-yatabe" to "Katsuyoshi Yatabe",
    "kawakubo-keiji" to "Kawakubo Keiji",
    "kawano-hotaru" to "Kawano Hotaru",
    "kazuya-kuroda" to "Kazuya Kuroda",
    "kazuyuki-honda" to "Kazuyuki Honda",
    "kenji-hattori" to "Kenji Hattori",
    "kikuchi-michitaka" to "Kikuchi Michitaka",
    "kimono" to "Kimono",
    "kimura-hiroshi" to "Kimura Hiroshi",
    "kimura-ryouichi" to "Kimura Ryouichi",
    "kimura-takeshi" to "Kimura Takeshi",
    "kinakonoyama-studio" to "Kinakonoyama Studio",
    "king-bee" to "King Bee",
    "kinhashi-takashi" to "Kinhashi Takashi",
    "kinji-yoshimoto" to "Kinji Yoshimoto",
    "kinohara-hikaru" to "Kinohara Hikaru",
    "kinomoto-natsumi" to "Kinomoto Natsumi",
    "kinta-kunte" to "Kinta Kunte",
    "kishizuka-kenji" to "Kishizuka Kenji",
    "kita-senju-ayase" to "Kita-Senju Ayase",
    "kitchen" to "Kitchen",
    "kitty-media" to "Kitty Media",
    "km-produce" to "Km-produce",
    "knack-productions" to "Knack Productions",
    "knight" to "Knight",
    "kohaku-sumeragi" to "Kohaku Sumeragi",
    "koio-minato" to "Koio Minato",
    "koishikawa-yuu" to "Koishikawa Yuu",
    "koji-tanaka" to "Koji Tanaka",
    "kokubunji-sousuke" to "Kokubunji Sousuke",
    "komai-kazuya" to "Komai Kazuya",
    "kondou-nobuhiro" to "Kondou Nobuhiro",
    "kondou-takashi" to "Kondou Takashi",
    "kor" to "KOR",
    "kotama-kasu" to "Kotama Kasu",
    "kotobuki-ranko" to "Kotobuki Ranko",
    "kou-tomi" to "Kou Tomi",
    "kouji-yamamoto" to "Kouji Yamamoto",
    "kume-issei" to "Kume Issei",
    "kuramori-rokurou" to "Kuramori Rokurou",
    "kuraya-ryouichi" to "Kuraya Ryouichi",
    "kurige-katsura" to "Kurige Katsura",
    "kurogane-kenn" to "Kurogane Kenn",
    "kurotsuguchi-narue" to "Kurotsuguchi Narue",
    "kurou-kawasaki" to "Kurou Kawasaki",
    "kusakawa-keizou" to "Kusakawa Keizou",
    "kushi-hideaki" to "Kushi Hideaki",
    "kyushu-network-animation" to "Kyushu Network Animation",
    "lactation" to "Lactation",
    "lemon-heart" to "Lemon Heart",
    "licking" to "Licking",
    "lilith" to "Lilith",
    "lingerie" to "Lingerie",
    "lolicon" to "Lolicon",
    "lune-pictures" to "Lune Pictures",
    "lune-soft-studio" to "Lune-soft Studio",
    "lyricbox-studio" to "lyricbox Studio",
    "madhouse" to "Madhouse",
    "magic-bus" to "Magic Bus",
    "magical-girl" to "Magical Girl",
    "magin-studio" to "Magin Studio",
    "maguro-teikoku" to "Maguro Teikoku",
    "maids" to "Maids",
    "majin" to "Majin",
    "makino-yoshitaka" to "Makino Yoshitaka",
    "makino-yukihiro" to "Makino Yukihiro",
    "mako" to "Mako",
    "makoto-sokuza" to "Makoto Sokuza",
    "mamito-tayama" to "Mamito Tayama",
    "mamoru-sakisaka" to "Mamoru Sakisaka",
    "manga-animation" to "Manga animation",
    "maplestar" to "Maplestar",
    "mary-jane" to "Mary Jane",
    "masa-puku" to "Masa Puku",
    "masaharu-tomoda" to "Masaharu Tomoda",
    "masaki-shinichi" to "Masaki Shinichi",
    "masato-yura" to "Masato Yura",
    "massage" to "Massage",
    "masturbation" to "Masturbation",
    "matano-ryuuzou2" to "Matano Ryuuzou",
    "matrix-studio" to "Matrix Studio",
    "matsugaoka-ken" to "Matsugaoka Ken",
    "matsumura-yasuhiro" to "Matsumura Yasuhiro",
    "mature" to "Mature",
    "media-blasters" to "Media Blasters",
    "mediabank" to "Mediabank",
    "medieval" to "Medieval",
    "melissa-studio" to "Melissa Studio",
    "meltdown-studio" to "Meltdown Studio",
    "metro-notes-studio" to "Metro Notes Studio",
    "mikan-fuyuno" to "Mikan Fuyuno",
    "mikazuki-kougetsu" to "Mikazuki Kougetsu",
    "milf" to "MILF",
    "military" to "Military",
    "milky" to "Milky Animation Label",
    "mimura-sougetsu" to "Mimura Sougetsu",
    "minamichou-sanjuurou" to "Minamichou Sanjuurou",
    "minamizawa-juuhachi" to "Minamizawa Juuhachi",
    "misaki-fuyukawa" to "Misaki Fuyukawa",
    "misumi-ran" to "Misumi Ran",
    "mitsui-kimiko" to "Mitsui Kimiko",
    "miura-saburou" to "Miura Saburou",
    "miyabi-tsuzuru" to "Miyabi Tsuzuru",
    "miyake-yuuichirou" to "Miyake Yuuichirou",
    "miyazaki-maya" to "Miyazaki Maya",
    "mizuno-kentarou" to "Mizuno Kentarou",
    "mizuno-takahiro" to "Mizuno Takahiro",
    "mizuryuu-kei" to "Mizuryuu Kei",
    "monsters" to "Monsters",
    "moon-rock" to "Moon Rock",
    "morino-usagi" to "Morino Usagi",
    "morishiba-jurin" to "Morishiba Jurin",
    "moriyama-yuji" to "Moriyama Yuji",
    "moriyama-yuuji" to "Moriyama Yuuji",
    "moriyasu-taniguchi" to "Moriyasu Taniguchi",
    "motonaga-keitarou" to "Motonaga Keitarou",
    "motoyama-yukitoshi" to "Motoyama Yukitoshi",
    "mousou-jitsugen-media" to "Mousou Jitsugen Media",
    "mousou-senka-studio" to "Mousou Senka Studio",
    "ms-pictures2" to "Ms-pictures",
    "mujitax" to "MujitaX",
    "murakami-koutarou" to "Murakami Koutarou",
    "murakami-teruaki" to "Murakami Teruaki",
    "murakami-tsunekazu" to "Murakami Tsunekazu",
    "muraki-kazuma" to "Muraki Kazuma",
    "murayama-kousuke" to "Murayama Kousuke",
    "music" to "Music",
    "mutto-studio" to "MUTTO STUDIO",
    "mv" to "MV",
    "mystic" to "Mystic",
    "nagahama-norihiko" to "Nagahama Norihiko",
    "najar" to "Najar",
    "nakajima-hiroaki" to "Nakajima Hiroaki",
    "nakamura-yuusuke" to "Nakamura Yuusuke",
    "nakasone-manabu" to "Nakasone Manabu",
    "nakazawa-kazuto" to "Nakazawa Kazuto",
    "nasubi-natsukawa" to "Nasubi Natsukawa",
    "natsu-kaze" to "Natsu Kaze",
    "natsume-isaku" to "Natsume Isaku",
    "new-generation" to "New Generation",
    "nighthawk" to "Nighthawk Studio",
    "nikkatsu-corporation" to "Nikkatsu Corporation",
    "nikkatsu-studio" to "Nikkatsu Studio",
    "ninja" to "Ninja",
    "nintai-akira" to "Nintai Akira",
    "nipple-fuck" to "Nipple Fuck",
    "nishijima-katsuhiko" to "Nishijima Katsuhiko",
    "nishikawa-takashi" to "Nishikawa Takashi",
    "nishimura-taiju" to "Nishimura Taiju",
    "nobitome-youta" to "Nobitome Youta",
    "noboru-jitsuhara" to "Noboru Jitsuhara",
    "noritomo-hattori" to "Noritomo Hattori",
    "noshitani-mitsutaka" to "Noshitani Mitsutaka",
    "nur-studio" to "Nur Studio",
    "nurse" to "Nurse",
    "nutech-digital" to "NuTech Digital",
    "o-hanemai" to "O Hanemai",
    "obtain-future-studio" to "Obtain Future Studio",
    "oda-kansaburou" to "Oda Kansaburou",
    "office-8-ban" to "Office 8-ban",
    "office-lady" to "Office Lady",
    "office-take-off" to "Office Takeout / Office Take Off",
    "ogino-satoshi" to "Ogino Satoshi",
    "ogura-kazuhiro" to "Ogura Kazuhiro",
    "ohara-kazuhiro" to "Ohara Kazuhiro",
    "ohtani-hajime" to "Ohtani Hajime",
    "oil" to "Oil",
    "okamoto-hideki" to "Okamoto Hideki",
    "okesawa-hisashi" to "Okesawa Hisashi",
    "onoda-yuusuke" to "Onoda Yuusuke",
    "oogawara-haruo" to "Oogawara Haruo",
    "oota-hideta" to "Oota Hideta",
    "oota-hiromitsu" to "Oota Hiromitsu",
    "oota-shuuta" to "Oota Shuuta",
    "ooyama-takashi" to "Ooyama Takashi",
    "oral-sex" to "Oral sex",
    "orc" to "Orc",
    "osuzu-akiomi" to "Osuzu Akiomi",
    "oz-inc" to "Oz Inc.",
    "parody" to "Parody",
    "party" to "Party",
    "pashminaa" to "PashminaA",
    "peak-hunt-studio" to "Peak Hunt Studio",
    "pet" to "Pet",
    "phoenix-entertainment" to "Phoenix Entertainment",
    "picante-circus-studio" to "Picante Circus Studio",
    "piercing" to "Piercing",
    "pinkpineapple" to "PinkPineapple",
    "pissing" to "Pissing",
    "pixy-studio" to "Pixy Studio",
    "police" to "Police",
    "poly-animation" to "POLY ANIMATION",
    "por" to "POR",
    "poro" to "PoRo",
    "pp-project" to "PP Project",
    "pregnant" to "Pregnant",
    "primetime" to "PrimeTime",
    "princess" to "Princess",
    "prison" to "Prison",
    "promo" to "Promo",
    "public-sex" to "Public / outdoor",
    "pyou-ryuu" to "Pyou Ryuu",
    "queen-bee" to "Queen Bee",
    "rabbit-gate" to "Rabbit Gate",
    "raika-ken" to "Raika Ken",
    "rape" to "Rape",
    "redhead" to "Redhead",
    "confession" to "Religion",
    "ribahara-aki" to "Ribahara Aki",
    "richard-taylor" to "Richard Taylor",
    "riddle-soft" to "Riddle Soft",
    "rinhee" to "Rinhee",
    "ripple-film" to "Ripple Film",
    "robots" to "Robots",
    "roku-iwata" to "Roku Iwata",
    "romance" to "Romance",
    "rus" to "Rus",
    "ryou-kanda" to "Ryou Kanda",
    "ryuu-m-s" to "Ryuu M's",
    "ryuuichi-nozaki" to "Ryuuichi Nozaki",
    "sadayama-yanaha" to "Sadayama Yanaha",
    "saishin-saide" to "Saishin Saide",
    "saitou-dousan" to "Saitou Dousan",
    "saitou-hisashi" to "Saitou Hisashi",
    "saitou-michizou" to "Saitou Michizou",
    "saitou-yoshinari" to "Saitou Yoshinari",
    "sakaki" to "SAKAKI",
    "sakimichan" to "SakimiChan",
    "sakuma-shuuji" to "Sakuma Shuuji",
    "sakura-momo" to "Sakura Momo",
    "samurai" to "Samurai",
    "sanbun-kyouden" to "Sanbun Kyouden",
    "sandwichworks" to "SANDWICHWORKS",
    "satoshi-urushihara" to "Satoshi Urushihara",
    "sawayama-shinichiro" to "Sawayama Shinichiro",
    "scat" to "Scat",
    "school" to "School",
    "schoolzone" to "Schoolzone Studio",
    "sci-fi" to "Sci-Fi",
    "sei-konno" to "Sei Konno",
    "seiji-okuda" to "Seiji Okuda",
    "seishin-seishutsu" to "Seishin Seishutsu",
    "selfish" to "SELFISH",
    "seven" to "Seven Studio",
    "sex-slave" to "Sex_slave",
    "shaved" to "Shaved",
    "shibari" to "Shibari",
    "shibire-hitsuji" to "Shibire Hitsuji",
    "shiei-jun" to "Shiei Jun",
    "shigenori-awai" to "Shigenori Awai",
    "shigenori-kurii" to "Shigenori Kurii",
    "shigeru-yazaki" to "Shigeru Yazaki",
    "shigeta-kentarou" to "Shigeta Kentarou",
    "shiina-yuuki" to "Shiina Yuuki",
    "shiki-takuto" to "Shiki Takuto",
    "shikishima-hirohide" to "Shikishima Hirohide",
    "shin-fujisaki" to "Shin Fujisaki",
    "shindeban-film" to "Shindeban Film",
    "shinichi-shimizu" to "Shinichi Shimizu",
    "shinji-tobita" to "Shinji Tobita",
    "shinjugai" to "Shinjugai",
    "shinkuukan" to "Shinkuukan",
    "shinmaruko-iku" to "Shinmaruko Iku",
    "shinozuka-yuuji" to "Shinozuka Yuuji",
    "shion-studio" to "Shion Studio",
    "sho-hanebu" to "Sho Hanebu",
    "short-film-series" to "Short_film_ series",
    "short-vid" to "Short_vid",
    "shotacon" to "Shotacon",
    "shounen-ai2" to "Shounen-Ai",
    "shower" to "Shower",
    "showten-studio" to "Showten Studio",
    "sido-limited" to "SIDO LIMITED",
    "sirius-studio" to "Sirius Studio",
    "slave" to "Slave",
    "slut" to "Slut",
    "small-tits" to "Small tits",
    "softcore" to "Softcore",
    "sorasochi-sumishi" to "Sorasochi Sumishi",
    "spa" to "Spa",
    "spoon" to "SPOON",
    "sports" to "Sports",
    "squirt" to "Squirt",
    "staple-entertainment" to "Staple Entertainment",
    "stockings" to "Stockings",
    "students" to "Students",
    "studio-1st" to "Studio 1st",
    "studio-9-maiami" to "Studio 9 Maiami",
    "studio-boogie-nights" to "Studio Boogie Nights",
    "studio-deen" to "Studio Deen",
    "studio-discovery" to "Studio Discovery",
    "studio-eromatick" to "Studio Eromatick",
    "studio-erurukku" to "Studio Erurukku",
    "studio-fantasia" to "Studio Fantasia",
    "studio-houkiboshi" to "Studio Houkiboshi",
    "studio-huan" to "STUDIO HUAN",
    "studio-jam" to "Studio JAM",
    "studio-jin" to "Studio Jin",
    "studio-kelmadick" to "Studio Kelmadick",
    "studio-kikan" to "Studio Kikan",
    "studio-kyuma" to "Studio Kyuma",
    "studio-leo" to "Studio LEO",
    "studio-mausu" to "Studio Mausu",
    "studio-mink" to "Studio Mink",
    "studio-pierrot" to "Studio Pierrot",
    "studio-rakugakiteikoku" to "Studio RakugakiTeikoku",
    "studio-tamashii" to "Studio Tamashii",
    "studio-ten-carat" to "Studio Ten Carat",
    "studio-zealot" to "Studio Zealot",
    "studio-zero-g" to "Studio Zero-G",
    "studio9" to "STUDIO9",
    "sueda-yoshifumi" to "Sueda Yoshifumi",
    "suginami-daifuku" to "Suginami Daifuku",
    "suiseisha-studio" to "Suiseisha Studio",
    "sumito-machida" to "Sumito Machida",
    "sumito-sasaki" to "Sumito Sasaki",
    "superhero" to "Superhero",
    "survive" to "Survive",
    "survive-more" to "Survive More",
    "suzuki-mirano" to "Suzuki Mirano",
    "swimsuit" to "Swimsuit",
    "t-rex" to "T-Rex",
    "tachibana-pan" to "Tachibana Pan",
    "taiichi-kitagawa" to "Taiichi Kitagawa",
    "takagi-hidefumi" to "Takagi Hidefumi",
    "takagi-ryo" to "Takagi Ryo",
    "takahane-shin" to "Takahane Shin",
    "takahashi-kaoru" to "Takahashi Kaoru",
    "takahashi-nariyuki" to "Takahashi Nariyuki",
    "takai-takashi" to "Takai Takashi",
    "takami-akio" to "Takami Akio",
    "takayama-hideki" to "Takayama Hideki",
    "takeda-hiromitsu" to "Takeda Hiromitsu",
    "takefumi-gouda" to "Takefumi Gouda",
    "takeo-takahashi" to "Takeo Takahashi",
    "takeshi-aoki" to "Takeshi Aoki",
    "takeshi-masui" to "Takeshi Masui",
    "takeshi-yamaguchi" to "Takeshi Yamaguchi",
    "takku" to "Takku",
    "taku" to "Taku",
    "tamae-kuwae" to "Tamae Kuwae",
    "tamaki-nana" to "Tamaki Nana",
    "tamaki-yousuke" to "Tamaki Yousuke",
    "tanaka-atsuji" to "Tanaka Atsuji",
    "taranbo-studio" to "Taranbo Studio",
    "taru-ippei" to "Taru Ippei",
    "tatsumi" to "Tatsumi",
    "tattoo" to "Tattoo",
    "teachers" to "Teachers",
    "teatro" to "TEATRO",
    "teatro-nishi-tokyo-studio" to "Teatro Nishi Tokyo Studio",
    "tentacles" to "Tentacles",
    "tenteke-ten" to "Tenteke Ten",
    "terakado-yasuhito" to "Terakado Yasuhito",
    "teruo-kogure" to "Teruo Kogure",
    "thai-pay-studio" to "Thai Pay Studio",
    "tinker-bell" to "Tinker Bell",
    "titsjob" to "Titsjob",
    "to-moriyama" to "To Moriyama",
    "toda-kazuhiro" to "Toda Kazuhiro",
    "toei-video" to "Toei Video",
    "tomi-tetsuyoshi" to "Tomi Tetsuyoshi",
    "tomii-wataru" to "Tomii Wataru",
    "tomizawa-kazuo" to "Tomizawa Kazuo",
    "tomoda-masaharu" to "Tomoda Masaharu",
    "toranoana" to "Toranoana",
    "torudaya-studio" to "Torudaya Studio",
    "toshiaki-komura" to "Toshiaki Komura",
    "toshiba-emi" to "Toshiba EMI",
    "toshiharu-sato" to "Toshiharu Sato",
    "toshio-takeuchi" to "Toshio Takeuchi",
    "toshiyuki-yamamoto" to "Toshiyuki Yamamoto",
    "totonito" to "Totonito",
    "toyooka-kaoru" to "Toyooka Kaoru",
    "toyota-manaka" to "Toyota Manaka",
    "trailer" to "Trailer",
    "trap" to "Trap",
    "triple-x" to "Triple X",
    "tsujimo-ga-machi-ni-yattekita" to "Tsujimo ga Machi ni Yattekita!!!",
    "tsujimura-umeko" to "Tsujimura Umeko",
    "tsukasa-kaidou" to "Tsukasa Kaidou",
    "tsunbeji-studio" to "Tsunbeji Studio",
    "tsutomu-mizushima" to "Tsutomu Mizushima",
    "twins" to "Twins",
    "tzoou-tour-jea" to "Tzoou Tour Jea",
    "uchiyama-aki" to "Uchiyama Aki",
    "no-censor" to "Uncensored",
    "uniform" to "Uniform",
    "ura-heru" to "Ura Heru",
    "urasuji-samurai" to "Urasuji Samurai",
    "ursaite-studio" to "Ursaite_Studio",
    "ushijima-yuuji" to "Ushijima Yuuji",
    "uzoike-zumishi" to "Uzoike Zumishi",
    "valkyria-animation-mode" to "Valkyria Studio",
    "vampire" to "Vampire",
    "vanilla-series" to "Vanilla Series",
    "violance" to "Violance",
    "virgin" to "Virgin",
    "wada-heisaku" to "Wada Heisaku",
    "watanabe-shinichi" to "Watanabe Shinichi",
    "watanabe-takashi" to "Watanabe Takashi",
    "watase-toshihiro" to "Watase Toshihiro",
    "white-bear" to "White Bear",
    "will-be-well-studio" to "WILL BE WELL Studio",
    "worldpg-anime-studio" to "WorldPG Anime Studio",
    "wstar-studio" to "Wstar Studio",
    "x-ray" to "X-Ray",
    "y-o-u-c" to "Y.O.U.C.",
    "yamamoto-motoyanagi" to "Yamamoto Motoyanagi",
    "yamamoto-naoki" to "Yamamoto Naoki",
    "yamamoto-yuusuke" to "Yamamoto Yuusuke",
    "yamane-ayano" to "YAMANE Ayano",
    "yamauchi-noriyasu" to "Yamauchi Noriyasu",
    "yanase-hiroyuki" to "Yanase Hiroyuki",
    "yaoi" to "Yaoi",
    "yasuhito-kikuchi" to "Yasuhito Kikuchi",
    "yasunori-urata" to "Yasunori Urata",
    "yasuomi-umetsu" to "Yasuomi Umetsu",
    "yoda-takeshi" to "Yoda Takeshi",
    "yokoyama-hiromi" to "Yokoyama Hiromi",
    "yokoyama-hitomi" to "Yokoyama Hitomi",
    "yokoyama-masamichi" to "Yokoyama Masamichi",
    "yoneda-mitsuhiro" to "Yoneda Mitsuhiro",
    "yoneta" to "Yoneta",
    "yorihisa-uchida" to "Yorihisa Uchida",
    "yoshida-tooru" to "Yoshida Tooru",
    "yoshihiro-oka" to "Yoshihiro Oka",
    "yoshikawa-kouji" to "Yoshikawa Kouji",
    "yoshimura-ai" to "Yoshimura Ai",
    "yoshisuke-yamaguchi" to "Yoshisuke Yamaguchi",
    "yoshiten" to "Yoshiten",
    "yoshizawa-akiho" to "Yoshizawa Akiho",
    "yousei-morino" to "Yousei Morino",
    "yozo" to "Yozo",
    "yuho-dou-studio" to "Yuho Dou Studio",
    "yuri" to "Yuri",
    "yusaku-saotome" to "Yusaku Saotome",
    "yutaro-mochizuki" to "Yutaro Mochizuki",
    "yuu-yahagi" to "Yuu Yahagi",
    "yuuei-studio" to "YUUEI STUDIO",
    "yuuki-shinjuurou" to "Yuuki Shinjuurou",
    "yuusaku-aoi" to "Yuusaku Aoi",
    "yuyama-kunihiko" to "Yuyama Kunihiko",
    "zexcs" to "Zexcs",
    "zion" to "ZION",
    "ziz" to "ZIZ",
    "zombie" to "Zombie",
    "star-studio" to "ωstar studio",
    "nimix" to "Аnimix",
)

internal val MODEL_TERMS: List<Pair<String, String>> = listOf(
    "a-p-p-p" to "A P P P",
    "a1c-studio" to "A1C Studio",
    "ahiru-koike" to "Ahiru Koike",
    "aic" to "Aic",
    "alice-soft" to "Alice Soft",
    "animac" to "Animac",
    "anime-antenna-iinkai" to "Anime Antenna Iinkai",
    "apataito-studio" to "Apataito Studio",
    "araki-hideki" to "Araki Hideki",
    "arms" to "ARMS",
    "asano-hiro" to "Asano Hiro",
    "awai-shigeki" to "Awai Shigeki",
    "ayano-kunio" to "Ayano Kunio",
    "bomb-cute-bomb" to "Bomb Cute Bomb",
    "bootleg" to "Bootleg",
    "breakbottle" to "Breakbottle",
    "chichi-no-ya" to "Chichi No Ya",
    "collaboration-works" to "Collaboration Works",
    "cyberframe-studio" to "Cyberframe Studio",
    "digital-works" to "Digital Works",
    "edge" to "Edge",
    "five-ways-studio" to "Five Ways Studio",
    "flavors-soft" to "Flavors Soft",
    "fujimoto-yoshitaka" to "Fujimoto Yoshitaka",
    "fukumoto-kan" to "Fukumoto Kan",
    "gold-bear" to "Gold Bear",
    "green-bunny" to "Green Bunny",
    "hamuo" to "Hamuo",
    "hayakawa-naomi" to "Hayakawa Naomi",
    "hideki-oota" to "Hideki Oota",
    "himajin" to "Himajin",
    "hiromi-yokoyama" to "Hiromi Yokoyama",
    "houkiboshi-studio" to "Houkiboshi Studio",
    "j-c-staff" to "J C Staff",
    "japananime" to "Japananime",
    "jinbou-masato" to "Jinbou Masato",
    "kaidou-tsukasa" to "Kaidou Tsukasa",
    "kajishima-masaki" to "Kajishima Masaki",
    "kanazawa-katsuma" to "Kanazawa Katsuma",
    "kasahara-shinpei" to "Kasahara Shinpei",
    "katsuma-kanazawa" to "Katsuma Kanazawa",
    "kazuyuki-honda" to "Kazuyuki Honda",
    "kimura-takeshi" to "Kimura Takeshi",
    "kitty-media" to "Kitty Media",
    "km-produce" to "Km Produce",
    "kokubunji-sousuke" to "Kokubunji Sousuke",
    "kondou-takashi" to "Kondou Takashi",
    "kotobuki-ranko" to "Kotobuki Ranko",
    "kurou-kawasaki" to "Kurou Kawasaki",
    "lilith" to "Lilith",
    "lune-soft" to "Lune Soft",
    "magic-bus" to "Magic Bus",
    "majin" to "Majin",
    "mary-jane" to "Mary Jane",
    "matano-ryuuzou" to "Matano Ryuuzou",
    "media-blasters" to "Media Blasters",
    "mediabank" to "Mediabank",
    "milky-animation-label" to "Milky Animation Label",
    "misumi-ran" to "Misumi Ran",
    "miura-saburou" to "Miura Saburou",
    "ms-pictures" to "Ms Pictures",
    "murakami-teruaki" to "Murakami Teruaki",
    "nagahama-norihiko" to "Nagahama Norihiko",
    "nighthawk-studio" to "Nighthawk Studio",
    "nishijima-katsuhiko" to "Nishijima Katsuhiko",
    "nishikawa-takashi" to "Nishikawa Takashi",
    "nobitome-youta" to "Nobitome Youta",
    "noshitani-mitsutaka" to "Noshitani Mitsutaka",
    "nur-studio" to "Nur Studio",
    "nutech-digital" to "Nutech Digital",
    "obtain-future-studio" to "Obtain Future Studio",
    "oda-kansaburou" to "Oda Kansaburou",
    "office-takeout" to "Office Takeout",
    "ogura-kazuhiro" to "Ogura Kazuhiro",
    "okesawa-hisashi" to "Okesawa Hisashi",
    "oota-hideta" to "Oota Hideta",
    "pashminaa" to "PashminaA",
    "picante-circus-studio" to "Picante Circus Studio",
    "pinkpineapple" to "Pinkpineapple",
    "pixy" to "Pixy",
    "poro" to "Poro",
    "queen-bee" to "Queen Bee",
    "raika-ken" to "Raika Ken",
    "sadayama-yanaha" to "Sadayama Yanaha",
    "sawayama-shinichiro" to "Sawayama Shinichiro",
    "schoolzone" to "Schoolzone",
    "selfish" to "Selfish",
    "seven-studio" to "Seven Studio",
    "shinichi-shimizu" to "Shinichi Shimizu",
    "sho-hanebu" to "Sho Hanebu",
    "showten-studio" to "Showten Studio",
    "studio-1st" to "Studio 1St",
    "studio-9-maiami" to "Studio 9 Maiami",
    "studio-discovery" to "Studio Discovery",
    "studio-eromatick" to "Studio Eromatick",
    "studio-fantasia" to "Studio Fantasia",
    "studio-jam" to "Studio Jam",
    "suginami-daifuku" to "Suginami Daifuku",
    "suiseisha-studio" to "Suiseisha Studio",
    "survive" to "Survive",
    "survive-more" to "Survive More",
    "suzuki-mirano" to "Suzuki Mirano",
    "t-rex" to "T Rex",
    "tenteke-ten" to "Tenteke Ten",
    "tinker-bell" to "Tinker Bell",
    "tomii-wataru" to "Tomii Wataru",
    "tsujimo-ga-machi-ni-yattekita" to "Tsujimo Ga Machi Ni Yattekita",
    "valkyria-studio" to "Valkyria Studio",
    "vanilla-series" to "Vanilla Series",
    "watase-toshihiro" to "Watase Toshihiro",
    "white-bear" to "White Bear",
    "y-o-u-c" to "Y O U C",
    "yokoyama-hiromi" to "Yokoyama Hiromi",
    "yoneda-mitsuhiro" to "Yoneda Mitsuhiro",
    "yoshiten" to "Yoshiten",
    "ziz" to "Ziz",
)
