/*lint:disable:standard:filename*/
package eu.kanade.tachiyomi.animeextension.all.hentaicity

/**
 * The site's tag vocabulary, from the /categories/ index, then validated one by
 * one: a tag only ships when /tags/video/{slug} actually renders videos. Slugs use
 * `+` for spaces (both the raw form and %20 are accepted by the site).
 */
internal val TAGS: List<Pair<String, String>> = listOf(
    "3d+anal" to "3d Anal",
    "3d+animation" to "3d Animation",
    "3d+big+tits" to "3d Big Tits",
    "3d+blonde" to "3d Blonde",
    "3d+blowjob" to "3d Blowjob",
    "3d+cartoon" to "3d Cartoon",
    "3d+comics" to "3d Comics",
    "3d+futanari" to "3d Futanari",
    "3d+hentai" to "3d Hentai",
    "3d+monster" to "3d Monster",
    "3d+sex" to "3d Sex",
    "3some" to "3some",
    "69" to "69",
    "alien" to "Alien",
    "anal+creampie" to "Anal Creampie",
    "anal+sex" to "Anal Sex",
    "anal+virgin" to "Anal Virgin",
    "angel" to "Angel",
    "animated" to "Animated",
    "animation" to "Animation",
    "anime" to "Anime",
    "ass+fucking" to "Ass Fucking",
    "asshole" to "Asshole",
    "bald+pussy" to "Bald Pussy",
    "bathroom" to "Bathroom",
    "bbc" to "Bbc",
    "bdsm" to "Bdsm",
    "beach" to "Beach",
    "beast" to "Beast",
    "bedroom" to "Bedroom",
    "big+ass" to "Big Ass",
    "big+black+cock" to "Big Black Cock",
    "big+boobs" to "Big Boobs",
    "big+cock" to "Big Cock",
    "big+cock+anal" to "Big Cock Anal",
    "big+cock+blowjob" to "Big Cock Blowjob",
    "big+dick+blowjob" to "Big Dick Blowjob",
    "big+dick+futanari" to "Big Dick Futanari",
    "big+monster+cock" to "Big Monster Cock",
    "big+monster+dick" to "Big Monster Dick",
    "big+tits+blowjob" to "Big Tits Blowjob",
    "big+tits+cumshot" to "Big Tits Cumshot",
    "big+tits+futanari" to "Big Tits Futanari",
    "big+tits+milf" to "Big Tits Milf",
    "big+tits+schoolgirl" to "Big Tits Schoolgirl",
    "big+tits+teen" to "Big Tits Teen",
    "bikini" to "Bikini",
    "black+cock" to "Black Cock",
    "black+dick" to "Black Dick",
    "blackmailed" to "Blackmailed",
    "blonde" to "Blonde",
    "blonde+big+tits" to "Blonde Big Tits",
    "blonde+teen" to "Blonde Teen",
    "bondage" to "Bondage",
    "boobjob" to "Boobjob",
    "boss" to "Boss",
    "boyfriend" to "Boyfriend",
    "brother" to "Brother",
    "brunette" to "Brunette",
    "busty" to "Busty",
    "busty+blonde" to "Busty Blonde",
    "busty+elf" to "Busty Elf",
    "busty+futanari" to "Busty Futanari",
    "busty+milf" to "Busty Milf",
    "busty+redhead" to "Busty Redhead",
    "busty+schoolgirl" to "Busty Schoolgirl",
    "busty+teen" to "Busty Teen",
    "catgirl" to "Catgirl",
    "chained" to "Chained",
    "cheating" to "Cheating",
    "classroom" to "Classroom",
    "college" to "College",
    "compilation" to "Compilation",
    "cosplay" to "Cosplay",
    "cowgirl" to "Cowgirl",
    "crazy" to "Crazy",
    "creampie" to "Creampie",
    "cum" to "Cum",
    "cum+in+mouth" to "Cum In Mouth",
    "cum+on+tits" to "Cum On Tits",
    "curvy" to "Curvy",
    "cute" to "Cute",
    "cute+teen" to "Cute Teen",
    "daughter" to "Daughter",
    "dead+or+alive" to "Dead Or Alive",
    "deepthroat" to "Deepthroat",
    "demon" to "Demon",
    "dildo" to "Dildo",
    "dirty" to "Dirty",
    "doctor" to "Doctor",
    "doggy+style" to "Doggy Style",
    "doggy+style+anal" to "Doggy Style Anal",
    "double+anal" to "Double Anal",
    "double+blowjob" to "Double Blowjob",
    "double+penetration" to "Double Penetration",
    "dungeon" to "Dungeon",
    "ebony" to "Ebony",
    "ecchi" to "Ecchi",
    "elf" to "Elf",
    "elf+princess" to "Elf Princess",
    "face+fuck" to "Face Fuck",
    "facial" to "Facial",
    "family" to "Family",
    "fantasy" to "Fantasy",
    "fighting" to "Fighting",
    "filmed" to "Filmed",
    "fingering" to "Fingering",
    "first+time" to "First Time",
    "footjob" to "Footjob",
    "foursome" to "Foursome",
    "fucking" to "Fucking",
    "funny" to "Funny",
    "furry" to "Furry",
    "futa" to "Futa",
    "futanari+blowjob" to "Futanari Blowjob",
    "game" to "Game",
    "gangbang" to "Gangbang",
    "gay+anal" to "Gay Anal",
    "girlfriend" to "Girlfriend",
    "glasses" to "Glasses",
    "hairy+pussy" to "Hairy Pussy",
    "handjob" to "Handjob",
    "hardcore" to "Hardcore",
    "harem" to "Harem",
    "hentai+anal" to "Hentai Anal",
    "hentai+blowjob" to "Hentai Blowjob",
    "hentai+monster" to "Hentai Monster",
    "high+heels" to "High Heels",
    "high+school" to "High School",
    "horny" to "Horny",
    "horror" to "Horror",
    "hospital" to "Hospital",
    "hotel" to "Hotel",
    "housewife" to "Housewife",
    "huge+cock" to "Huge Cock",
    "huge+dick" to "Huge Dick",
    "huge+tits" to "Huge Tits",
    "interracial" to "Interracial",
    "interracial+sex" to "Interracial Sex",
    "japanese" to "Japanese",
    "jizz" to "Jizz",
    "kinky" to "Kinky",
    "kissing" to "Kissing",
    "licking+tits" to "Licking Tits",
    "lingerie" to "Lingerie",
    "locker+room" to "Locker Room",
    "love+potion" to "Love Potion",
    "maid" to "Maid",
    "married" to "Married",
    "masturbating" to "Masturbating",
    "mature+big+tits" to "Mature Big Tits",
    "milf" to "Milf",
    "mind+control" to "Mind Control",
    "moaning" to "Moaning",
    "mom" to "Mom",
    "monster+anal" to "Monster Anal",
    "monster+blowjob" to "Monster Blowjob",
    "mother" to "Mother",
    "muscular" to "Muscular",
    "music+video" to "Music Video",
    "nerd" to "Nerd",
    "ntr" to "Ntr",
    "nurse" to "Nurse",
    "office" to "Office",
    "old+and+young" to "Old And Young",
    "old+man" to "Old Man",
    "on+her+knees" to "On Her Knees",
    "oral" to "Oral",
    "orc" to "Orc",
    "orgasm" to "Orgasm",
    "orgy" to "Orgy",
    "outdoors" to "Outdoors",
    "overwatch" to "Overwatch",
    "overwatch+compilation" to "Overwatch Compilation",
    "panties" to "Panties",
    "pervert" to "Pervert",
    "petite" to "Petite",
    "petite+teen" to "Petite Teen",
    "pigtails" to "Pigtails",
    "pissing" to "Pissing",
    "ponytail" to "Ponytail",
    "pov" to "Pov",
    "pregnant" to "Pregnant",
    "princess" to "Princess",
    "public" to "Public",
    "public+blowjob" to "Public Blowjob",
    "public+sex" to "Public Sex",
    "pussy" to "Pussy",
    "pussy+licking" to "Pussy Licking",
    "redhead" to "Redhead",
    "redhead+big+tits" to "Redhead Big Tits",
    "redhead+teen" to "Redhead Teen",
    "romantic" to "Romantic",
    "school" to "School",
    "schoolgirl" to "Schoolgirl",
    "schoolgirl+blowjob" to "Schoolgirl Blowjob",
    "schoolgirl+groupsex" to "Schoolgirl Groupsex",
    "schoolgirl+uniform" to "Schoolgirl Uniform",
    "scifi" to "Scifi",
    "senpai" to "Senpai",
    "sensei" to "Sensei",
    "sex" to "Sex",
    "sex+toys" to "Sex Toys",
    "sexy" to "Sexy",
    "sfm" to "Sfm",
    "shaved+pussy" to "Shaved Pussy",
    "shemale" to "Shemale",
    "short+hair" to "Short Hair",
    "shower" to "Shower",
    "shy" to "Shy",
    "sister" to "Sister",
    "slave" to "Slave",
    "sleeping" to "Sleeping",
    "slut" to "Slut",
    "small+tits" to "Small Tits",
    "softcore" to "Softcore",
    "son" to "Son",
    "sports" to "Sports",
    "squirting" to "Squirting",
    "stepsister" to "Stepsister",
    "stockings" to "Stockings",
    "storyline" to "Storyline",
    "strapon" to "Strapon",
    "student" to "Student",
    "succubus" to "Succubus",
    "swimsuit" to "Swimsuit",
    "taboo" to "Taboo",
    "teacher" to "Teacher",
    "teacher+and+student" to "Teacher And Student",
    "teen+anal" to "Teen Anal",
    "teen+blowjob" to "Teen Blowjob",
    "teen+boobjob" to "Teen Boobjob",
    "teen+creampie" to "Teen Creampie",
    "teen+cumshot" to "Teen Cumshot",
    "teen+groupsex" to "Teen Groupsex",
    "teen+threesome" to "Teen Threesome",
    "tentacles" to "Tentacles",
    "threesome" to "Threesome",
    "tied+up" to "Tied Up",
    "tight+pussy" to "Tight Pussy",
    "titty+fuck" to "Titty Fuck",
    "train" to "Train",
    "ugly+bastard" to "Ugly Bastard",
    "uncensored" to "Uncensored",
    "uncensored+hentai" to "Uncensored Hentai",
    "uniform" to "Uniform",
    "vibrator" to "Vibrator",
    "virgin" to "Virgin",
    "warrior" to "Warrior",
    "watching" to "Watching",
    "weird" to "Weird",
    "wet+pussy" to "Wet Pussy",
    "wife" to "Wife",
    "xray" to "Xray",
    "young" to "Young",
    "zombie" to "Zombie",
)
