/*lint:disable:standard:filename*/
package eu.kanade.tachiyomi.animeextension.all.hentaistream

// The site's full genre taxonomy, harvested from /genres (522 entries).
// Each label is the exact string the site prints in a card's "Genre(s):" line,
// which is what makes include/exclude enforceable on the parsed rows.
// Sorted A-Z.
internal val GENRE_NAMES = arrayOf(
    "Absurdist Humour", "Action", "Action Game", "Adventure", "Age Difference Romance", "Ahegao",
    "Air Force", "Alcohol", "Alien", "Aliens", "Aliens Living on Earth", "All-Girls School",
    "Alternative Past", "Alternative Present", "Anal", "Anal Fingering", "Anal Pissing", "Android",
    "Androids", "Angel", "Angels", "Angst", "Animal Abuse", "Anime", "Anthropomorphism", "Archery",
    "Art", "Asia", "Ass-Kicking Girls", "Assjob", "Aunt-Nephew Incest", "Autofellatio",
    "Bad Cooking", "Bakumatsu - Meiji Era", "Bakunyuu", "Banana Peel", "Band", "Baseball",
    "Basketball", "Battle Royale", "BDSM", "Beach Visit", "Beautiful People Club", "Bestiality",
    "Big Breasts", "Bishoujo", "Bishounen", "Black Humour", "Blackmail", "Body and Host",
    "Body Exchange", "Body Sharing", "Body Takeover", "Boing", "Bondage", "Boobjob",
    "Boobs in your Face", "Borderline Porn", "Boy Meets Girl", "Brainwashing", "Breast Expansion",
    "Breast Fondling", "Breasts", "Brother-Sister Incest", "Bukkake", "Bullying", "Busty",
    "Call My Name", "Calling Your Attacks", "Catgirls", "Catholic School", "Censored",
    "Cervix Penetration", "Chemical Weapons", "Chikan", "Christianity", "Christmas", "Clone",
    "Clubs", "Collateral Damage", "College", "Combat", "Comedy", "Coming of Age", "Competition",
    "Computer", "Confession", "Conspiracy", "Contemporary Fantasy", "Cooking", "Cops",
    "Cosplaying", "Countryside", "Couple", "Cream Pie", "Crime", "Cross-Dressing", "Cum Play",
    "Cum Swapping", "Cunnilingus", "Cybersex", "Cyborg", "Cyborgs", "Cycling", "Daikaijuu",
    "Daily Life", "Damsel in Distress", "Dark Elf", "Dark Fantasy", "Dark-Skinned Girl",
    "Dating Sim - Visual Novel", "Death", "Defeat Means Friendship", "Deflowering", "Deity",
    "Delinquent", "Demon", "Demons", "Desert", "Detective", "Dildos", "Dildos - Vibrators",
    "Disaster", "Doggy Style", "Dominatrix", "Double Fellatio", "Double Penetration",
    "Double-Sided Dildo", "Dragon", "Dragons", "Drastic Change of Life", "Drugs", "Dungeon",
    "Dystopia", "Ecchi", "Elf", "Elves", "Emotions Awaken Superpowers", "End of the World",
    "Enema", "Engaged to an Alien", "English Dubbed", "Enjo-Kousai", "Enjoyable Rape",
    "Erotic Asphyxiation", "Erotic Game", "Erotic Torture", "Everybody Has Sex", "Exhibitionism",
    "Exorcism", "Eyeball Licking", "Faceless Alien Invasion", "Facesitting", "Facial Distortion",
    "Fairy", "Family Life", "Fantasy", "Fantasy World", "Fate", "Father-Daughter Incest",
    "Felching", "Fellatio", "Female Rapes Female", "Female Student", "Female Students",
    "Female Teacher", "Female Teachers", "Femdom", "FFM Threesome", "Fictional Location",
    "Fictional World", "Fighting", "Fingering", "First Kiss", "First Love", "Fisting",
    "Flat Chest Jokes", "Foot Fetish", "Footjob", "Forbidden Love", "Foreskin Sex",
    "Formerly One-Gender School", "Foursome", "French Kiss", "Friendship", "Funny Expressions",
    "Futa x Female", "Futa x Futa", "Futa x Male", "Futanari", "Future", "Gainax Bounce", "Game",
    "Gang Bang", "Gang Rape", "Gangbang", "Gender Bender", "Genetic Modification", "Genocide",
    "Ghost", "Gigantic Breasts", "Girl Rapes Girl", "Glory Hole", "Goblin", "Goddess", "Goddesses",
    "Gokkun", "Golden Shower", "Gore", "Greek Mythology", "Groping", "Group", "Group Sex",
    "Gunfights", "Guy Getting Raped", "Gymnastics", "Hand Job", "Handjob", "Hard-Working", "Harem",
    "Hell", "Helpful", "Henshin", "Hentai Haven", "Heroic Sacrifice", "Hidden Vibrator",
    "High Fantasy", "High School", "Historical", "Horny Nosebleed", "Horror", "Hospital",
    "Hostage Situation", "Housewives", "Huge Breasts", "Human Cannibalism", "Human Enhancement",
    "Human Experimentation", "Human Sacrifice", "Humanoid", "Humanoid Alien", "Idol",
    "Important Haircut", "Impregnation", "Incest", "Infidelity", "Internal Shots", "Island",
    "Japanese Mythology", "Jealousy", "Josei", "Jungle", "Juujin", "Kidnapping", "Lactation",
    "Large Breasts", "Law and Order", "Licking Vagina", "Lingerie", "Loli", "Lolicon",
    "Lost Technology", "Love Polygon", "Mafia", "Magic", "Magic Circles", "Magic Weapons",
    "Magical Girl", "Mahou Shoujo", "Maid", "Maids", "Male Rape Victim", "Mammary Intercourse",
    "Manga", "Martial Arts", "Massacre", "Master-Servant Relationship", "Master-Slave Relation",
    "Masturbation", "Mecha", "Mechanical Tentacle", "Mechanical Tentacles", "Medium Awareness",
    "Medium Breasts", "Mermaid", "Middle School", "Military", "Military is Useless",
    "MMF Threesome", "MMM Threesome", "Molestation", "Money", "Monster of the Week",
    "Mother-Daughter Incest", "Mother-Son Incest", "Multiple Couples", "Mundane Made Awesome",
    "Murder", "Murder of Family Members", "Music", "Mutilation", "Mythology", "Naked Apron",
    "Necrophilia", "Netorare", "Netori", "Ninja", "Ninjas", "Nipple Penetration",
    "Norse Mythology", "Nostril Hook", "Novel", "Nudity", "Nun", "Nurse", "Nurses", "Nyotaimori",
    "Office Lady", "Onahole", "Oral", "Orgy", "Other Planet", "Outdoor Sex", "Oyakodon", "Paizuri",
    "Pantsu", "Pantyjob", "Paper Clothes", "Parallel Universe", "Parasites",
    "Parental Abandonment", "Parody", "Pegging", "Penis Jokes", "Performance", "Petplay",
    "Pillory", "Piloted Robots", "Plot Continuity", "Plot With Porn", "Point of View",
    "Pornography", "Post-apocalypse", "Post-Apocalypse", "Post-apocalyptic", "Post-Apocalyptic",
    "POV", "Power Gives You Wings", "Power Suit", "Predominantly Adult Cast",
    "Predominantly Female Cast", "Pregnant Sex", "Prostate Massage", "Prostitution",
    "Proxy Battles", "Psychological Sexual Abuse", "Public Sex", "Pussy in your Face",
    "Pussy Sandwich", "Racism", "Randomness", "Rape", "Red-Light District", "Religion", "Revenge",
    "Reverse Trap", "Rimming", "Rivalry", "Robot", "Robot Helper", "Romance", "RPG", "Running Gag",
    "Safer Sex", "Samurai", "Satire", "Saving the World", "Scat", "School", "School Clubs",
    "School Excursion", "School Life", "School Swimsuit", "Sci-Fi", "Science and Magic Coexist",
    "Science Fiction", "Scissoring", "Seinen", "Seiyuu", "Self-Parody", "Sex", "Sex Change",
    "Sex Doll", "Sex Tape", "Sex Toys", "Sex While on the Phone", "Sexual Abuse",
    "Sexual Fantasies", "Sexual Humour", "Sexually Dominant", "Shibari", "Shipboard", "Shool Life",
    "Short Episodes", "Shota", "Shotacon", "Shoujo", "Shoujo Ai", "Shounen", "Shounen Ai",
    "Sibling Yin Yang", "Sister-Sister Incest", "Sixty-Nine", "Skimpy Clothing", "Skirt Flipping",
    "Slapstick", "Slavery", "Sleeping Sex", "Slow When It Comes To Love", "Small Breasts",
    "Soapland", "Social Commentary", "Sociocultural Evolution", "Space", "Space Travel",
    "Spanking", "Special Squads", "Speculative Fiction", "Spellcasting", "Spirit Realm", "Sports",
    "Squirting", "Stereotypes", "Stomach Bulge", "Stomach Stretch", "Strapon", "Strappado Bondage",
    "Strong Female Lead", "Strong Male Lead", "Student Government", "Submission", "Succubus",
    "Sudden Girlfriend Appearance", "Sudden Naked Girl Appearance", "Sudden Naked Guy Appearance",
    "Sumata", "Summoning", "Super Deformed", "Super Power", "Swimsuit", "Swordplay",
    "Teacher x Student", "Telepathy", "Tennis", "Tentacle", "Tentacles", "Terrorism",
    "The Power of Love", "Thigh Sex", "Threesome", "Threesome With Sisters", "Thriller",
    "Throat Fucking", "Time Travel", "Toilet Humour", "Tokyo Destroyed", "Torture", "Tournament",
    "Tragedy", "Transfer Student", "Trap", "Traps", "Triple Penetration", "Tropes", "Tsundere",
    "Twincest", "Twisted", "Uncensored", "Uncle-Niece Incest", "Undead", "Under One Roof",
    "Underworld", "Uniform Fetish", "Unrequited Love", "Urethra Penetration", "Urination",
    "Urophagia", "Vampire", "Vibrators", "Video Game Development", "Violence",
    "Violent Retribution for Accidental Infringement", "Virgin", "Virginity", "Virgins",
    "Virtual Reality", "Visible Aura", "Visual Novel", "Volleyball", "Voyeurism", "Vulgar",
    "Waitress", "Waitresses", "Wakamezake", "War", "Wardrobe Malfunction", "Water Sex", "Wax Play",
    "Whip", "Whipping", "Whips", "Window Fuck", "Wooden Horse", "Wordplay", "Working Life",
    "Wrestling", "Yakuza", "Yaoi", "Yuri", "Zettai Ryouiki", "Zombie", "Zombies",
)

// The site's own /genres?genre=<slug> identifiers, index-aligned with GENRE_NAMES.
internal val GENRE_SLUGS = arrayOf(
    "Absurdist_Humour", "Action", "Action_Game", "Adventure", "Age_Difference_Romance", "Ahegao",
    "Air_Force", "Alcohol", "Alien", "Aliens", "Aliens_Living_on_Earth", "All-Girls_School",
    "Alternative_Past", "Alternative_Present", "Anal", "Anal_Fingering", "Anal_Pissing", "Android",
    "Androids", "Angel", "Angels", "Angst", "Animal_Abuse", "Anime", "Anthropomorphism", "Archery",
    "Art", "Asia", "Ass-Kicking_Girls", "Assjob", "Aunt-Nephew_Incest", "Autofellatio",
    "Bad_Cooking", "Bakumatsu_-_Meiji_Era", "Bakunyuu", "Banana_Peel", "Band", "Baseball",
    "Basketball", "Battle_Royale", "BDSM", "Beach_Visit", "Beautiful_People_Club", "Bestiality",
    "Big_Breasts", "Bishoujo", "Bishounen", "Black_Humour", "Blackmail", "Body_and_Host",
    "Body_Exchange", "Body_Sharing", "Body_Takeover", "Boing", "Bondage", "Boobjob",
    "Boobs_in_your_Face", "Borderline_Porn", "Boy_Meets_Girl", "Brainwashing", "Breast_Expansion",
    "Breast_Fondling", "Breasts", "Brother-Sister_Incest", "Bukkake", "Bullying", "Busty",
    "Call_My_Name", "Calling_Your_Attacks", "Catgirls", "Catholic_School", "Censored",
    "Cervix_Penetration", "Chemical_Weapons", "Chikan", "Christianity", "Christmas", "Clone",
    "Clubs", "Collateral_Damage", "College", "Combat", "Comedy", "Coming_of_Age", "Competition",
    "Computer", "Confession", "Conspiracy", "Contemporary_Fantasy", "Cooking", "Cops",
    "Cosplaying", "Countryside", "Couple", "Cream_Pie", "Crime", "Cross-Dressing", "Cum_Play",
    "Cum_Swapping", "Cunnilingus", "Cybersex", "Cyborg", "Cyborgs", "Cycling", "Daikaijuu",
    "Daily_Life", "Damsel_in_Distress", "Dark_Elf", "Dark_Fantasy", "Dark-Skinned_Girl",
    "Dating_Sim_-_Visual_Novel", "Death", "Defeat_Means_Friendship", "Deflowering", "Deity",
    "Delinquent", "Demon", "Demons", "Desert", "Detective", "Dildos", "Dildos_-_Vibrators",
    "Disaster", "Doggy_Style", "Dominatrix", "Double_Fellatio", "Double_Penetration",
    "Double-Sided_Dildo", "Dragon", "Dragons", "Drastic_Change_of_Life", "Drugs", "Dungeon",
    "Dystopia", "Ecchi", "Elf", "Elves", "Emotions_Awaken_Superpowers", "End_of_the_World",
    "Enema", "Engaged_to_an_Alien", "English_Dubbed", "Enjo-Kousai", "Enjoyable_Rape",
    "Erotic_Asphyxiation", "Erotic_Game", "Erotic_Torture", "Everybody_Has_Sex", "Exhibitionism",
    "Exorcism", "Eyeball_Licking", "Faceless_Alien_Invasion", "Facesitting", "Facial_Distortion",
    "Fairy", "Family_Life", "Fantasy", "Fantasy_World", "Fate", "Father-Daughter_Incest",
    "Felching", "Fellatio", "Female_Rapes_Female", "Female_Student", "Female_Students",
    "Female_Teacher", "Female_Teachers", "Femdom", "FFM_Threesome", "Fictional_Location",
    "Fictional_World", "Fighting", "Fingering", "First_Kiss", "First_Love", "Fisting",
    "Flat_Chest_Jokes", "Foot_Fetish", "Footjob", "Forbidden_Love", "Foreskin_Sex",
    "Formerly_One-Gender_School", "Foursome", "French_Kiss", "Friendship", "Funny_Expressions",
    "Futa_x_Female", "Futa_x_Futa", "Futa_x_Male", "Futanari", "Future", "Gainax_Bounce", "Game",
    "Gang_Bang", "Gang_Rape", "Gangbang", "Gender_Bender", "Genetic_Modification", "Genocide",
    "Ghost", "Gigantic_Breasts", "Girl_Rapes_Girl", "Glory_Hole", "Goblin", "Goddess", "Goddesses",
    "Gokkun", "Golden_Shower", "Gore", "Greek_Mythology", "Groping", "Group", "Group_Sex",
    "Gunfights", "Guy_Getting_Raped", "Gymnastics", "Hand_Job", "Handjob", "Hard-Working", "Harem",
    "Hell", "Helpful", "Henshin", "Hentai_Haven", "Heroic_Sacrifice", "Hidden_Vibrator",
    "High_Fantasy", "High_School", "Historical", "Horny_Nosebleed", "Horror", "Hospital",
    "Hostage_Situation", "Housewives", "Huge_Breasts", "Human_Cannibalism", "Human_Enhancement",
    "Human_Experimentation", "Human_Sacrifice", "Humanoid", "Humanoid_Alien", "Idol",
    "Important_Haircut", "Impregnation", "Incest", "Infidelity", "Internal_Shots", "Island",
    "Japanese_Mythology", "Jealousy", "Josei", "Jungle", "Juujin", "Kidnapping", "Lactation",
    "Large_Breasts", "Law_and_Order", "Licking_Vagina", "Lingerie", "Loli", "Lolicon",
    "Lost_Technology", "Love_Polygon", "Mafia", "Magic", "Magic_Circles", "Magic_Weapons",
    "Magical_Girl", "Mahou_Shoujo", "Maid", "Maids", "Male_Rape_Victim", "Mammary_Intercourse",
    "Manga", "Martial_Arts", "Massacre", "Master-Servant_Relationship", "Master-Slave_Relation",
    "Masturbation", "Mecha", "Mechanical_Tentacle", "Mechanical_Tentacles", "Medium_Awareness",
    "Medium_Breasts", "Mermaid", "Middle_School", "Military", "Military_is_Useless",
    "MMF_Threesome", "MMM_Threesome", "Molestation", "Money", "Monster_of_the_Week",
    "Mother-Daughter_Incest", "Mother-Son_Incest", "Multiple_Couples", "Mundane_Made_Awesome",
    "Murder", "Murder_of_Family_Members", "Music", "Mutilation", "Mythology", "Naked_Apron",
    "Necrophilia", "Netorare", "Netori", "Ninja", "Ninjas", "Nipple_Penetration",
    "Norse_Mythology", "Nostril_Hook", "Novel", "Nudity", "Nun", "Nurse", "Nurses", "Nyotaimori",
    "Office_Lady", "Onahole", "Oral", "Orgy", "Other_Planet", "Outdoor_Sex", "Oyakodon", "Paizuri",
    "Pantsu", "Pantyjob", "Paper_Clothes", "Parallel_Universe", "Parasites",
    "Parental_Abandonment", "Parody", "Pegging", "Penis_Jokes", "Performance", "Petplay",
    "Pillory", "Piloted_Robots", "Plot_Continuity", "Plot_With_Porn", "Point_of_View",
    "Pornography", "Post-apocalypse", "Post-Apocalypse", "Post-apocalyptic", "Post-Apocalyptic",
    "POV", "Power_Gives_You_Wings", "Power_Suit", "Predominantly_Adult_Cast",
    "Predominantly_Female_Cast", "Pregnant_Sex", "Prostate_Massage", "Prostitution",
    "Proxy_Battles", "Psychological_Sexual_Abuse", "Public_Sex", "Pussy_in_your_Face",
    "Pussy_Sandwich", "Racism", "Randomness", "Rape", "Red-Light_District", "Religion", "Revenge",
    "Reverse_Trap", "Rimming", "Rivalry", "Robot", "Robot_Helper", "Romance", "RPG", "Running_Gag",
    "Safer_Sex", "Samurai", "Satire", "Saving_the_World", "Scat", "School", "School_Clubs",
    "School_Excursion", "School_Life", "School_Swimsuit", "Sci-Fi", "Science_and_Magic_Coexist",
    "Science_Fiction", "Scissoring", "Seinen", "Seiyuu", "Self-Parody", "Sex", "Sex_Change",
    "Sex_Doll", "Sex_Tape", "Sex_Toys", "Sex_While_on_the_Phone", "Sexual_Abuse",
    "Sexual_Fantasies", "Sexual_Humour", "Sexually_Dominant", "Shibari", "Shipboard", "Shool_Life",
    "Short_Episodes", "Shota", "Shotacon", "Shoujo", "Shoujo_Ai", "Shounen", "Shounen_Ai",
    "Sibling_Yin_Yang", "Sister-Sister_Incest", "Sixty-Nine", "Skimpy_Clothing", "Skirt_Flipping",
    "Slapstick", "Slavery", "Sleeping_Sex", "Slow_When_It_Comes_To_Love", "Small_Breasts",
    "Soapland", "Social_Commentary", "Sociocultural_Evolution", "Space", "Space_Travel",
    "Spanking", "Special_Squads", "Speculative_Fiction", "Spellcasting", "Spirit_Realm", "Sports",
    "Squirting", "Stereotypes", "Stomach_Bulge", "Stomach_Stretch", "Strapon", "Strappado_Bondage",
    "Strong_Female_Lead", "Strong_Male_Lead", "Student_Government", "Submission", "Succubus",
    "Sudden_Girlfriend_Appearance", "Sudden_Naked_Girl_Appearance", "Sudden_Naked_Guy_Appearance",
    "Sumata", "Summoning", "Super_Deformed", "Super_Power", "Swimsuit", "Swordplay",
    "Teacher_x_Student", "Telepathy", "Tennis", "Tentacle", "Tentacles", "Terrorism",
    "The_Power_of_Love", "Thigh_Sex", "Threesome", "Threesome_With_Sisters", "Thriller",
    "Throat_Fucking", "Time_Travel", "Toilet_Humour", "Tokyo_Destroyed", "Torture", "Tournament",
    "Tragedy", "Transfer_Student", "Trap", "Traps", "Triple_Penetration", "Tropes", "Tsundere",
    "Twincest", "Twisted", "Uncensored", "Uncle-Niece_Incest", "Undead", "Under_One_Roof",
    "Underworld", "Uniform_Fetish", "Unrequited_Love", "Urethra_Penetration", "Urination",
    "Urophagia", "Vampire", "Vibrators", "Video_Game_Development", "Violence",
    "Violent_Retribution_for_Accidental_Infringement", "Virgin", "Virginity", "Virgins",
    "Virtual_Reality", "Visible_Aura", "Visual_Novel", "Volleyball", "Voyeurism", "Vulgar",
    "Waitress", "Waitresses", "Wakamezake", "War", "Wardrobe_Malfunction", "Water_Sex", "Wax_Play",
    "Whip", "Whipping", "Whips", "Window_Fuck", "Wooden_Horse", "Wordplay", "Working_Life",
    "Wrestling", "Yakuza", "Yaoi", "Yuri", "Zettai_Ryouiki", "Zombie", "Zombies",
)
