package eu.kanade.tachiyomi.animeextension.all.hentaiheaven

import eu.kanade.tachiyomi.animesource.model.AnimeFilter
import eu.kanade.tachiyomi.animesource.model.AnimeFilterList
import eu.kanade.tachiyomi.animesource.model.AnimesPage
import eu.kanade.tachiyomi.animesource.model.SAnime
import eu.kanade.tachiyomi.animesource.model.SEpisode
import eu.kanade.tachiyomi.animesource.model.Video
import eu.kanade.tachiyomi.animesource.online.AnimeHttpSource
import eu.kanade.tachiyomi.network.GET
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.longOrNull
import okhttp3.Headers
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.Response
import org.jsoup.Jsoup
import uy.kohesive.injekt.injectLazy

/**
 * HentaiHeaven mirrors the hanime.tv catalogue.
 *
 * The legacy JSON APIs (search.htv-services.workers.dev, members.hanime.tv) are
 * gone. Listings, search, filters and details are served by the current public
 * guest search API, which returns the whole catalogue in a single request;
 * sorting, filtering and pagination are done client-side.
 *
 * Video streams require a signed manifest (x-signature headers generated by
 * hanime.tv's WASM client), which is not available to plain HTTP clients.
 */
class HentaiHeaven : AnimeHttpSource() {

    override val name = "HentaiHeaven"

    override val baseUrl = "https://hentaiheaven.xxx"

    override val lang = "all"

    override val supportsLatest = true

    override val client: OkHttpClient = network.client

    private val json: Json by injectLazy()

    private val searchApiUrl = "https://guest.freeanimehentai.net/api/v11/search_hvs"
    private val guestManifestUrl = "https://guest.freeanimehentai.net/api/v8/guest/videos"

    private val pageSize = 24
    private val cacheTtlMs = 10 * 60 * 1000L

    @Volatile
    private var cachedHits: List<JsonObject>? = null

    @Volatile
    private var cacheTimestamp = 0L

    override fun headersBuilder(): Headers.Builder = Headers.Builder()
        .add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36")
        .add("Accept", "application/json")
        .add("Origin", "https://hanime.tv")
        .add("Referer", "https://hanime.tv/")

    // ============================== Catalogue cache ==============================

    private fun fetchHits(): List<JsonObject> {
        val cached = cachedHits
        if (cached != null && System.currentTimeMillis() - cacheTimestamp < cacheTtlMs) {
            return cached
        }

        val response = client.newCall(GET(searchApiUrl, headers)).execute()
        response.use {
            val body = it.body.string()
            if (it.isSuccessful && body.isNotBlank()) {
                val root = json.parseToJsonElement(body)
                val array: JsonArray = if (root is JsonObject) {
                    root["data"]?.jsonArray ?: JsonArray(emptyList())
                } else {
                    root.jsonArray
                }
                val hits = array.map { entry -> entry.jsonObject }
                cachedHits = hits
                cacheTimestamp = System.currentTimeMillis()
                return hits
            }
        }
        throw Exception("HentaiHeaven: catalogue request failed (${response.code})")
    }

    private fun hitString(hit: JsonObject, key: String): String =
        hit[key]?.jsonPrimitive?.content ?: ""

    private fun hitLong(hit: JsonObject, key: String): Long =
        hit[key]?.jsonPrimitive?.longOrNull ?: 0L

    private fun hitTags(hit: JsonObject): List<String> =
        hit["tags"]?.jsonArray?.map { it.jsonPrimitive.content } ?: emptyList()

    private fun hitToAnime(hit: JsonObject): SAnime = SAnime.create().apply {
        val slug = hitString(hit, "slug")
        url = "/videos/hentai/$slug"
        title = hitString(hit, "name")
        thumbnail_url = hitString(hit, "cover_url").ifEmpty { hitString(hit, "poster_url") }
        initialized = true
    }

    private fun paginate(hits: List<JsonObject>, page: Int): AnimesPage {
        val from = (page - 1).coerceAtLeast(0) * pageSize
        if (from >= hits.size) return AnimesPage(emptyList(), false)
        val to = (from + pageSize).coerceAtMost(hits.size)
        val list = hits.subList(from, to).map { hitToAnime(it) }
        return AnimesPage(list, to < hits.size)
    }

    private fun sortedHits(hits: List<JsonObject>, sortKey: String, descending: Boolean): List<JsonObject> =
        if (descending) {
            hits.sortedByDescending { hitLong(it, sortKey) }
        } else {
            hits.sortedBy { hitLong(it, sortKey) }
        }

    // ============================== Popular Anime ==============================

    override fun popularAnimeRequest(page: Int): Request =
        GET("$searchApiUrl?hh_page=$page&sort=views", headers)

    override fun popularAnimeParse(response: Response): AnimesPage {
        val hits = fetchHits()
        return paginate(sortedHits(hits, "views", descending = true), pageFromResponse(response))
    }

    private fun pageFromResponse(response: Response): Int =
        response.request.url.queryParameter("hh_page")?.toIntOrNull() ?: 1

    // ============================== Latest Updates ==============================

    override fun latestUpdatesRequest(page: Int): Request =
        GET("$searchApiUrl?hh_page=$page&sort=created_at_unix", headers)

    override fun latestUpdatesParse(response: Response): AnimesPage {
        val hits = fetchHits()
        return paginate(sortedHits(hits, "created_at_unix", descending = true), pageFromResponse(response))
    }

    // ============================== Search ==============================

    override fun searchAnimeRequest(page: Int, query: String, filters: AnimeFilterList): Request {
        val url = searchApiUrl.toHttpUrl().newBuilder().apply {
            addQueryParameter("hh_page", page.toString())
            addQueryParameter("hh_query", query)
            getSearchParameters(filters).forEach { (key, value) ->
                addQueryParameter(key, value)
            }
        }.build()
        return GET(url.toString(), headers)
    }

    override fun searchAnimeParse(response: Response): AnimesPage {
        val url = response.request.url
        val page = url.queryParameter("hh_page")?.toIntOrNull() ?: 1
        val query = url.queryParameter("hh_query").orEmpty()
        val sortKey = url.queryParameter("hh_sort") ?: "views"
        val descending = url.queryParameter("hh_order") != "asc"
        val tags = url.queryParameter("hh_tags")?.split(",")?.filter { it.isNotBlank() }.orEmpty()
        val tagsAnd = url.queryParameter("hh_tmode") == "and"

        var hits = fetchHits()
        if (query.isNotBlank()) {
            val q = query.lowercase()
            hits = hits.filter { hit ->
                hitString(hit, "name").lowercase().contains(q) ||
                    hitString(hit, "search_titles").lowercase().contains(q)
            }
        }
        if (tags.isNotEmpty()) {
            hits = hits.filter { hit ->
                val hitTags = hitTags(hit)
                if (tagsAnd) tags.all { it in hitTags } else tags.any { it in hitTags }
            }
        }
        return paginate(sortedHits(hits, sortKey, descending), page)
    }

    // ============================== Filters ==============================

    private class SortFilter : AnimeFilter.Select<String>(
        "Sort by",
        arrayOf("Most viewed", "Most liked", "Newest", "Release date", "Most downloaded"),
        0,
    ) {
        val sortKey: String
            get() = when (state) {
                1 -> "likes"
                2 -> "created_at_unix"
                3 -> "released_at_unix"
                4 -> "downloads"
                else -> "views"
            }
    }

    private class OrderFilter : AnimeFilter.Select<String>(
        "Order",
        arrayOf("Descending", "Ascending"),
        0,
    ) {
        val descending: Boolean
            get() = state == 0
    }

    private class TagsModeFilter : AnimeFilter.Select<String>(
        "Tag matching",
        arrayOf("Match any selected tag", "Match all selected tags"),
        0,
    ) {
        val isAnd: Boolean
            get() = state == 1
    }

    private class GenreCheckbox(name: String) : AnimeFilter.CheckBox(name)

    private class GenreFilter(
        genres: Array<String>,
    ) : AnimeFilter.Group<AnimeFilter.CheckBox>("Genres", genres.map { GenreCheckbox(it) }) {
        val selected: List<String>
            get() = state.filter { it.state }.map { it.name }
    }

    private fun getSearchParameters(filters: AnimeFilterList): List<Pair<String, String>> {
        var sortKey = "views"
        var descending = true
        var tags: List<String> = emptyList()
        var tagsAnd = false

        filters.forEach { filter ->
            when (filter) {
                is SortFilter -> sortKey = filter.sortKey
                is OrderFilter -> descending = filter.descending
                is TagsModeFilter -> tagsAnd = filter.isAnd
                is GenreFilter -> tags = filter.selected
                else -> {}
            }
        }

        val params = mutableListOf(
            "hh_sort" to sortKey,
            "hh_order" to if (descending) "desc" else "asc",
            "hh_tmode" to if (tagsAnd) "and" else "or",
        )
        if (tags.isNotEmpty()) params.add("hh_tags" to tags.joinToString(","))
        return params
    }

    override fun getFilterList(): AnimeFilterList = AnimeFilterList(
        AnimeFilter.Header("Text search matches title and aliases"),
        SortFilter(),
        OrderFilter(),
        AnimeFilter.Separator(),
        TagsModeFilter(),
        GenreFilter(GENRE_TAGS),
    )

    // ============================== Anime Details ==============================

    override fun animeDetailsRequest(anime: SAnime): Request =
        GET("$baseUrl${anime.url}", headers)

    override fun animeDetailsParse(response: Response): SAnime {
        val slug = response.request.url.encodedPath.substringAfterLast("/")

        // Preferred: details straight from the cached catalogue hit.
        val hit = fetchHits().firstOrNull { hitString(it, "slug") == slug }
        if (hit != null) {
            return SAnime.create().apply {
                title = hitString(hit, "name")
                thumbnail_url = hitString(hit, "cover_url").ifEmpty { hitString(hit, "poster_url") }
                author = hitString(hit, "brand")
                description = Jsoup.parse(hitString(hit, "description")).text()
                genre = hitTags(hit).joinToString(", ")
                status = SAnime.COMPLETED
                initialized = true
            }
        }

        // Fallback: scrape the watch page meta tags.
        val document = Jsoup.parse(response.body.string())
        return SAnime.create().apply {
            title = document.selectFirst("meta[property=og:title]")?.attr("content")?.removeSuffix(" - hanime.tv") ?: slug
            thumbnail_url = document.selectFirst("meta[property=og:image]")?.attr("content")
            description = document.selectFirst("meta[property=og:description]")?.attr("content")
            status = SAnime.COMPLETED
            initialized = true
        }
    }

    // ============================== Episodes ==============================

    override fun episodeListRequest(anime: SAnime): Request =
        animeDetailsRequest(anime)

    override fun episodeListParse(response: Response): List<SEpisode> {
        val slug = response.request.url.encodedPath.substringAfterLast("/")
        val hit = fetchHits().firstOrNull { hitString(it, "slug") == slug }

        return listOf(
            SEpisode.create().apply {
                name = "Episode 1"
                episode_number = 1f
                url = "/videos/hentai/$slug"
                if (hit != null) {
                    val released = hitLong(hit, "released_at_unix")
                    val created = hitLong(hit, "created_at_unix")
                    date_upload = (if (released > 0) released else created) * 1000L
                }
            },
        )
    }

    // ============================== Video Streams ==============================
    //
    // Real stream manifests require hanime.tv's signed requests (x-signature
    // headers generated in the site's WASM bundle), which plain HTTP clients
    // cannot produce. The guest manifest endpoint is attempted first in case
    // it is ever opened up; otherwise playback fails with a clear message.

    override fun videoListRequest(episode: SEpisode): Request {
        val slug = episode.url.substringAfterLast("/")
        val hvId = fetchHits().firstOrNull { hitString(it, "slug") == slug }
            ?.get("id")?.jsonPrimitive?.longOrNull
            ?: throw Exception("HentaiHeaven: video not found for '$slug'")
        return GET(
            "$guestManifestUrl/$hvId/manifest",
            headers.newBuilder().apply {
                set("Referer", "https://player.hanime.tv/")
                set("Origin", "https://player.hanime.tv")
            }.build(),
        )
    }

    override fun videoListParse(response: Response): List<Video> {
        if (!response.isSuccessful) {
            throw Exception(
                "HentaiHeaven: video streams are protected by hanime.tv's signed " +
                    "request scheme (HTTP ${response.code}) and cannot be extracted yet.",
            )
        }
        val root = json.parseToJsonElement(response.body.string()).jsonObject
        val servers = root["servers"]?.jsonArray ?: return emptyList()

        val videos = mutableListOf<Video>()
        servers.forEach { serverElem ->
            val server = serverElem.jsonObject
            val serverName = server["name"]?.jsonPrimitive?.content ?: "HentaiHeaven"
            server["streams"]?.jsonArray?.forEach { streamElem ->
                val stream = streamElem.jsonObject
                val streamUrl = stream["url"]?.jsonPrimitive?.content ?: return@forEach
                if (streamUrl.isBlank()) return@forEach
                val height = stream["height"]?.jsonPrimitive?.content ?: "?"
                videos.add(Video(streamUrl, "$serverName • ${height}p", streamUrl))
            }
        }
        return videos.sortedByDescending { it.quality }
    }

    private companion object {
        private val GENRE_TAGS = arrayOf(
            "3d", "ahegao", "anal", "bdsm", "big boobs", "blow job", "bondage", "boob job",
            "censored", "comedy", "cosplay", "creampie", "dark skin", "facial", "fantasy",
            "filmed", "foot job", "gangbang", "glasses", "hand job", "harem", "hd", "horror",
            "incest", "inflation", "lactation", "maid", "masturbation", "mind break",
            "mind control", "monster", "nekomimi", "ntr", "nurse", "orgy", "plot", "pov",
            "pregnant", "public sex", "rimjob", "school girl", "scat", "softcore", "swimsuit",
            "teacher", "tentacle", "threesome", "toys", "trap", "tsundere", "ugly bastard",
            "uncensored", "vanilla", "virgin", "watersports", "x-ray", "yaoi", "yuri",
        )
    }
}
