/*lint:disable:standard:filename*/
package eu.kanade.tachiyomi.animeextension.all.hstream

/**
 * Tag and studio vocabulary, read off the filter panel the site's own /search
 * page renders (Livewire checkboxes), then validated one by one: a term only
 * ships when its search request returns cards, so no ticked box can land on an
 * empty page.
 */
internal val TAGS: List<Pair<String, String>> = listOf(
    "3d" to "3D",
    "48fps" to "48Fps",
    "4k" to "4K",
    "4k-48fps" to "4K 48Fps",
    "ahegao" to "Ahegao",
    "anal" to "Anal",
    "bdsm" to "Bdsm",
    "bestiality" to "Bestiality",
    "big-boobs" to "Big Boobs",
    "blow-job" to "Blow Job",
    "bondage" to "Bondage",
    "boob-job" to "Boob Job",
    "censored" to "Censored",
    "comedy" to "Comedy",
    "cosplay" to "Cosplay",
    "creampie" to "Creampie",
    "dark-skin" to "Dark Skin",
    "elf" to "Elf",
    "facial" to "Facial",
    "fantasy" to "Fantasy",
    "filmed" to "Filmed",
    "foot-job" to "Foot Job",
    "futanari" to "Futanari",
    "gangbang" to "Gangbang",
    "glasses" to "Glasses",
    "gore" to "Gore",
    "hand-job" to "Hand Job",
    "harem" to "Harem",
    "horror" to "Horror",
    "incest" to "Incest",
    "inflation" to "Inflation",
    "lactation" to "Lactation",
    "lq" to "Lq",
    "maid" to "Maid",
    "masturbation" to "Masturbation",
    "milf" to "Milf",
    "mind-break" to "Mind Break",
    "mind-control" to "Mind Control",
    "monster" to "Monster",
    "nekomimi" to "Nekomimi",
    "ntr" to "Ntr",
    "nurse" to "Nurse",
    "orc" to "Orc",
    "orgy" to "Orgy",
    "pov" to "Pov",
    "pregnant" to "Pregnant",
    "public-sex" to "Public Sex",
    "rape" to "Rape",
    "reverse-rape" to "Reverse Rape",
    "rimjob" to "Rimjob",
    "scat" to "Scat",
    "school-girl" to "School Girl",
    "small-boobs" to "Small Boobs",
    "succubus" to "Succubus",
    "swim-suit" to "Swim Suit",
    "teacher" to "Teacher",
    "tentacle" to "Tentacle",
    "threesome" to "Threesome",
    "toys" to "Toys",
    "trap" to "Trap",
    "tsundere" to "Tsundere",
    "ugly-bastard" to "Ugly Bastard",
    "uncensored" to "Uncensored",
    "vanilla" to "Vanilla",
    "virgin" to "Virgin",
    "x-ray" to "X-Ray",
    "yuri" to "Yuri",
)

internal val STUDIOS: List<Pair<String, String>> = listOf(
    "arms" to "Arms",
    "blue-eyes" to "Blue Eyes",
    "bomb-cute-bomb" to "BOMB! CUTE! BOMB!",
    "breakbottle" to "BreakBottle",
    "cherrylips" to "CherryLips",
    "chichinoya" to "ChiChinoya",
    "circle-tribute" to "Circle Tribute",
    "collaboration-works" to "Collaboration Works",
    "cranberry" to "Cranberry",
    "digital-works" to "Digital Works",
    "discovery" to "Discovery",
    "edge" to "Edge",
    "five-ways" to "Five Ways",
    "flavors-soft" to "Flavors Soft",
    "frontier-works" to "Frontier Works",
    "gold-bear" to "Gold Bear",
    "green-bunny" to "Green Bunny",
    "himajin-planning" to "Himajin Planning",
    "king-bee" to "King Bee",
    "l" to "L.",
    "lune-pictures" to "Lune Pictures",
    "magic-bus" to "Magic Bus",
    "majin" to "Majin",
    "mary-jane" to "Mary Jane",
    "media-blasters" to "Media Blasters",
    "mediabank" to "Mediabank",
    "metro-notes" to "Metro Notes",
    "milky-animation-label" to "Milky Animation Label",
    "moon-rock" to "Moon Rock",
    "mousou-jitsugen-media" to "Mousou Jitsugen Media",
    "mousou-senka" to "Mousou Senka",
    "ms-pictures" to "MS Pictures",
    "nihikime-no-dozeu" to "Nihikime no Dozeu",
    "nur" to "Nur",
    "pashmina" to "Pashmina",
    "peak-hunt" to "Peak Hunt",
    "pink-pineapple" to "Pink Pineapple",
    "pixy" to "Pixy",
    "pixy-soft" to "Pixy Soft",
    "poro" to "PoRO",
    "queen-bee" to "Queen Bee",
    "rabbit-gate" to "Rabbit Gate",
    "ryuu-ms" to "Ryuu M&#039;s",
    "schoolzone" to "Schoolzone",
    "selfish" to "SELFISH",
    "seven" to "Seven",
    "shinjukuza" to "Shinjukuza",
    "shinkuukan" to "Shinkuukan",
    "showten" to "Showten",
    "speed" to "SPEED",
    "studio-1st" to "Studio 1st",
    "studio-9-maiami" to "Studio 9 Maiami",
    "studio-fantasia" to "Studio Fantasia",
    "studio-ten" to "Studio Ten",
    "suiseisha" to "Suiseisha",
    "suzuki-mirano" to "Suzuki Mirano",
    "t-rex" to "T-Rex",
    "toranoana" to "Toranoana",
    "torudaya" to "Torudaya",
    "union-cho" to "Union Cho",
    "valkyria" to "Valkyria",
    "white-bear" to "White Bear",
    "xter" to "XTER",
    "ziz" to "ZIZ",
    "zyc" to "Zyc",
)
